import { timestamp, uuid } from "drizzle-orm/pg-core";

/** Standard primary key: a random UUID generated by Postgres. */
export const pk = () => uuid("id").primaryKey().defaultRandom();

/** created_at / updated_at, timezone-aware, defaulted to now(). */
export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
};
